apiVersion: v1
kind: Namespace
metadata:
  name: publishers
spec: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: publishers
  name: publisher
  annotations:
    iam.gke.io/gcp-service-account: main-service-account@pubsub-benchmark.iam.gserviceaccount.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: publishers
  name: publisher
  labels:
    app: publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      labels:
        app: publisher
      namespace: publishers
    spec:
      tolerations:
        - key: role
          operator: Equal
          value: publishers
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-nodepool
                    operator: In
                    values:
                      - publishers-pool
      serviceAccount: publisher
      containers:
        - image: europe-west9-docker.pkg.dev/pubsub-benchmark/pubsub-node/pubsub-node:stable
          name: publisher
          args: ["node", "index.js", "publish"]
          env:
            - name: TOPIC
              value: projects/pubsub-benchmark/topics/node-topic
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              memory: "32Mi"
              cpu: "250m"
            limits:
              memory: "64Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: publisher
  namespace: publishers
  name: publisher
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: http
  selector:
    app: publisher
